const CURRENCY_CODES = {
  USD: 'US',
  EUR: 'FR', // Euro
  JPY: 'JP',
  GBP: 'GB',
  AUD: 'AU',
  CAD: 'CA',
  CHF: 'CH',
  CNY: 'CN',
  SEK: 'SE',
  NZD: 'NZ',
  MXN: 'MX',
  SGD: 'SG',
  HKD: 'HK',
  NOK: 'NO',
  KRW: 'KR',
  TRY: 'TR',
  RUB: 'RU',
  INR: 'IN',
  BRL: 'BR',
  ZAR: 'ZA',
  DKK: 'DK',
  PLN: 'PL',
  TWD: 'TW',
  THB: 'TH',
  ILS: 'IL',
  CLP: 'CL',
  COP: 'CO',
  PEN: 'PE',
  ARS: 'AR',
  AED: 'AE',
  MUR: 'MU',
  VND: 'VN',
  MYR: 'MY',
  PHP: 'PH',
  KWD: 'KW',
  BGN: 'BG',
  HUF: 'HU',
  CZK: 'CZ',
  RON: 'RO',
  HRK: 'HR',
  DOP: 'DO',
  MAD: 'MA',
  LKR: 'LK',
  TND: 'TN',
  JOD: 'JO',
  OMR: 'OM',
  BHD: 'BH',
  KES: 'KE',
  UAH: 'UA',
  KZT: 'KZ',
  GEL: 'GE',
  AMD: 'AM',
  MNT: 'MN',
  NIO: 'NI',
  XOF: 'BF', // West African CFA Franc
  XAF: 'CF', // Central African CFA Franc
  XPF: 'PF', // CFP Franc
  ANG: 'CW', // Netherlands Antillean Guilder (represented by Curaçao)
  PAB: 'PA',
  BBD: 'BB',
  BZD: 'BZ',
  BMD: 'BM',
  GMD: 'GM',
  GNF: 'GN',
  KHR: 'KH',
  LAK: 'LA',
  MOP: 'MO',
  MWK: 'MW',
  MGA: 'MG',
  RWF: 'RW',
  STN: 'ST',
  SRD: 'SR',
  TMT: 'TM'
};
